apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
    spec:
      containers:
      - env:
        - name: GF_ALERTING_NOTIFICATION_TIMEOUT_SECONDS
          value: "60"
        - name: GF_BASICAUTH
          value: "true"
        - name: GF_BASICAUTHPASSWORD
        - name: GF_BASICAUTHUSER
        - name: GF_BASICAUTHUSER-WITHCREDENTIALS
          value: "true"
        - name: GF_ENV_DATASOURCE_URL
          value: http://elasticsearch:9200
        - name: GF_ENV_INDEX
        - name: GF_LOG_FILTERS
          value: rendering:debug
        - name: GF_RENDERING_CALLBACK_URL
          value: http://grafana:3000
        - name: GF_RENDERING_SERVER_URL
          value: http://renderer:8081/render
        - name: GF_SEARCH_MAX_BUCKETS
          value: "80000"
        - name: GF_TLSAUTH
          value: "true"
        - name: GF_TLSAUTHWITHCACERT
          value: "true"
        - name: GF_TLSSKIPVERIFY
          value: "true"
        image: ghcr.io/timebeat-app/grafana:3.0.1
        name: grafana
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
      restartPolicy: Always
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-storage
status: {}
